# Generated by Django 5.2.3 on 2025-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('deck', models.TextField()),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default='default/book.jpg', null=True, upload_to='books-imges/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
